# what is the total_revenue generated by male vs female customers

select sum(purchase_amount) , gender from customers c group by gender;

# which customers used discount but still spent more than the avg purchase amount ?

select * from customers where UPPER(Discount_Applied) = 'YES' and purchase_amount > (select avg(purchase_amount)  from customers);

# which are the top 5 products with the highest avg review rating ?

select round(avg(c1.Review_Rating),2) as products , c1.Item_Purchased  from customers c1 
 group by c1.Item_Purchased  order by round(avg(c1.Review_Rating),2) desc limit 5;
 
 # Compare the average purchase amounts between standard and express shippings 
 
select round(avg(case when lower(Shipping_Type) = 'standard' then purchase_amount end ),2)as 'std_purchase_amt' , 
round(avg(case when lower(Shipping_Type) = 'express' then purchase_amount end ),2)as 'express_purchase_amt' 
from customers where lower(Shipping_Type) in ('standard' , 'express') ;

# Do subscribed customers spent more ? Compare avg spent and total revenue between subscribers and non-subscribers 

select avg(purchase_amount) as 'average_spent' , sum(purchase_amount) as 'total_revenu' , Subscription_Status from customers 
group by Subscription_Status; -- Subscription_Status

# which 5 products have the highest percentage of purchases with discounts applied ?
select * from customers ;
select Item_Purchased , 
round(100*sum(case when Discount_Applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_applied 
 from customers group by Item_Purchased order by 2 desc limit 5;
 
 # Segments the customers into New , Returning and Loyal based on their total number of previous purchases  and show the count of each segment 
 # Hint : if a customer purchased a product 1 time (New customers)
 # Puchased between 2 and 10 times (Returning CUstomer) 
 # > 10 times (Loyal customer)
 
SELECT count(Customer_Segment) as 'Number_of_customers' , customer_segment FROM (
select Customer_ID , case when Previous_Purchases = 1 then 'New_Customer'
when Previous_Purchases between 1 and 10 then 'Returning_Customer'  when Previous_Purchases >= 10 then 'Loyal_customer' end as 'Customer_Segment'  
from customers group by Customer_ID , Previous_Purchases) kk group by customer_segment ;

# What are the top 3 most purchased products within each category ?

with cte as (
select Item_Purchased , Category , count(Customer_ID) as cust_Id  ,
row_number() over(partition by category  order by count(Customer_ID) desc) as rnk
from customers group by Item_Purchased , Category order by category , count(Customer_ID) desc
) 
select Item_Purchased, Category, cust_Id from cte where rnk <= 3 
;

# Are customers who are repeat buyers (more than 5 previous purchases) likely to subscribe  ?

select Subscription_Status , count(Customer_ID) as 'Repeat_Buyers' from customers where Previous_Purchases > 5 group by  Subscription_Status ;

# What is the revenue contribution of each age group 

select Age_group , sum(purchase_amount) as 'Revenue_Contribution' from customers group by Age_group order by sum(purchase_amount) desc;


 
 

 

